### PR TITLE
Fix exclamation comment

### PR DESCRIPTION
**Pull request by linktohack**
In a simpler manner

The previous one fails in this case:
!-------------------
!I'm a good comment
!-------------------
function good(a, b)
- The second comment line is not treated as comment, even worse, the
  apostrophe (') marks the rest as a string.
- The 4th line is not treated as a function even if there is no
  apostrophe.

### CODE REVIEW

**Comment by infininight** [comment]
What application and version are you seeing this problem with? The master branch is designed to work with TextMate 2.0 which I am not seeing the error described with. There is a 1.x branch for 1.x and other applications that haven't been updated yet.

**Comment by linktohack** [comment]
This happened to both Sublime Text 2 & 3.

Can you explains what's improved here, @infininight? https://github.com/textmate/fortran.tmbundle/commit/1f4489248fbc27c67f0a037e73373c00f03a3677

-L

**Comment by infininight** [comment]
The new rule scopes the whitespace leading into a comment (if any) separately from the comment, this means certain snippets continue to work before the comment, etc. This fails in Sublime Text because it doesn't recognize the `\G` assertion used in the end rule of the first begin/end.

The same change was made to all of the TextMate bundles because in a lot of them we scoped comments as a single match which didn't allow injections to work inside of comments. (Not a worry in Sublime Text as it also doesn't support injections as far as I know.)

**Comment by linktohack** [comment]
Thank you, @infininight, I got the idea, I will think of a universal way to work with them both.

**Pull request closed without merging**
